version: '3.3'

services:

  #mongo database
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - backend_demo:/data/db
    networks:
          - example-net

  #mysql database
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - backend_demo:/var/lib/sql
  
    networks:
          - example-net

  #Node APP
  nodejs:
    build: ./
    container_name: nodejsserver
    volumes:
      - .:/usr/src/app

    depends_on: [mongo,mysql]

    networks:
          - example-net

  nginx:
        build:
            context: ./

        container_name: ngnix
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./data/nginx:/etc/nginx/conf.d
        certbot:
          image: certbot/certbot
        
        depends_on:
          - nodejs

        networks:
          - example-net

volumes:
  backend_demo:

networks:
  example-net:
    external: true



